### ISSUE TITLE
Library does not compile on Ubuntu 14.04

### ISSUE THREAD

**Issue by dignakov** [roxlu/video_capture#1]
Hi, I was trying to compile the library on Ubuntu 14.04, and it seems to be failing. At first I was getting errors about undeclaired 'printf' statements, which I fixed by including stdio in Types.h

However now I'm getting more errors. I've attached the output:

---

---

---

---

-- VideoCapture.USE_GENERATE_X86: On
-- VideoCapture.USE_GENERATE_IPHONE: Off
-- VideoCapture.USE_GENERATE_IPHONE_SIMULATOR: Off
-- VideoCapture.USE_GENERATE_RPI: Off
-- VideoCapture.USE_OPENGL: On
-- VideoCapture.USE_DECKLINK: Off
-- Configuring done
-- Generating done
-- Build files have been written to: /home/dmitri/Code/test/video_capture-master/build/build.release
+ cmake --build . --target install --config Release
[ 70%] Built target videocapture
Linking CXX executable api_example
libvideocapture.a(V4L2_Capture.cpp.o): In function `ca::V4L2_Capture::getDevicesV4L2()':
V4L2_Capture.cpp:(.text+0x136c): undefined reference to`udev_new'
V4L2_Capture.cpp:(.text+0x1380): undefined reference to `udev_enumerate_new'
V4L2_Capture.cpp:(.text+0x1395): undefined reference to`udev_enumerate_add_match_subsystem'
V4L2_Capture.cpp:(.text+0x139d): undefined reference to `udev_enumerate_scan_devices'
V4L2_Capture.cpp:(.text+0x13a5): undefined reference to`udev_enumerate_get_list_entry'
V4L2_Capture.cpp:(.text+0x13f0): undefined reference to `udev_list_entry_get_next'
V4L2_Capture.cpp:(.text+0x1404): undefined reference to`udev_list_entry_get_name'
V4L2_Capture.cpp:(.text+0x1412): undefined reference to `udev_device_new_from_syspath'
V4L2_Capture.cpp:(.text+0x1430): undefined reference to`udev_device_get_devnode'
V4L2_Capture.cpp:(.text+0x1482): undefined reference to `udev_device_get_parent_with_subsystem_devtype'
V4L2_Capture.cpp:(.text+0x149b): undefined reference to`udev_device_get_sysattr_value'
V4L2_Capture.cpp:(.text+0x14c2): undefined reference to `udev_device_get_sysattr_value'
V4L2_Capture.cpp:(.text+0x15c6): undefined reference to`udev_enumerate_unref'
V4L2_Capture.cpp:(.text+0x15ce): undefined reference to `udev_unref'
collect2: error: ld returned 1 exit status
make[2]: **\* [api_example] Error 1
make[1]: **\* [CMakeFiles/api_example.dir/all] Error 2
make: **\* [all] Error 2
+ cd /home/dmitri/Code/test/video_capture-master/build/../install/linux-gcc-x86_64/bin
./release_x86.sh: 26: cd: can't cd to /home/dmitri/Code/test/video_capture-master/build/../install/linux-gcc-x86_64/bin
+ ./easy_opengl_example
./release_x86.sh: 28: ./release_x86.sh: ./easy_opengl_example: not found

**Comment by roxlu** [comment]
Hey dignakov sorry for the super late reply; didn't see your message. I develop on Mac and Arch Linux but haven't tested it on Linux for a while. I have to make a couple of changes to the Windows and Linux capture classes which I'll quickly; I'll check this issue then too. 

Update:
try installing libudev

**Comment by dignakov** [comment]
Hi, thanks for looking into this.

After trying to compile this is what  I get now:
(I'll try it on Arch later tonight, and a fresh install of Ubuntu)

---

---

---

\+ cd build.release
+ cmake -DCMAKE_BUILD_TYPE=Debug -DUSE_OPENGL=On -DUSE_GENERATE_X86=On -DUSE_GENERATE_IPHONE=Off -DUSE_GENERATE_IPHONE_SIMULATOR=Off -DUSE_GENERATE_RPI=Off -DUSE_DECKLINK=Off -DEXTERN_LIB_DIR=/home/dmitri/Code/test/video_capture-master/build/../extern/linux-gcc-x86_64/lib -DEXTERN_INC_DIR=/home/dmitri/Code/test/video_capture-master/build/../extern/linux-gcc-x86_64/include -DEXTERN_SRC_DIR=/home/dmitri/Code/test/video_capture-master/build/../extern/linux-gcc-x86_64/src -DTINYLIB_DIR=/home/dmitri/Code/test/video_capture-master/build/sources/tinylib/ -DCMAKE_INSTALL_PREFIX=/home/dmitri/Code/test/video_capture-master/build/../install/linux-gcc-x86_64 ../
-\- The C compiler identification is GNU 4.8.2
-\- The CXX compiler identification is GNU 4.8.2
-\- Check for working C compiler: /usr/bin/cc
-\- Check for working C compiler: /usr/bin/cc -- works
-\- Detecting C compiler ABI info
-\- Detecting C compiler ABI info - done
-\- Check for working CXX compiler: /usr/bin/c++
-\- Check for working CXX compiler: /usr/bin/c++ -- works
-\- Detecting CXX compiler ABI info
-\- Detecting CXX compiler ABI info - done
-\- VideoCapture.USE_GENERATE_X86: On
-\- VideoCapture.USE_GENERATE_IPHONE: Off
-\- VideoCapture.USE_GENERATE_IPHONE_SIMULATOR: Off
-\- VideoCapture.USE_GENERATE_RPI: Off
-\- VideoCapture.USE_OPENGL: On
-\- VideoCapture.USE_DECKLINK: Off
-\- Configuring done
-\- Generating done
-\- Build files have been written to: /home/dmitri/Code/test/video_capture-master/build/build.release
+ cmake --build . --target install --config Release
Scanning dependencies of target videocapture
[  7%] Building CXX object CMakeFiles/videocapture.dir/home/dmitri/Code/test/video_capture-master/src/videocapture/Base.cpp.o
[ 15%] Building CXX object CMakeFiles/videocapture.dir/home/dmitri/Code/test/video_capture-master/src/videocapture/Capture.cpp.o
[ 23%] Building CXX object CMakeFiles/videocapture.dir/home/dmitri/Code/test/video_capture-master/src/videocapture/Types.cpp.o
[ 30%] Building CXX object CMakeFiles/videocapture.dir/home/dmitri/Code/test/video_capture-master/src/videocapture/Utils.cpp.o
[ 38%] Building CXX object CMakeFiles/videocapture.dir/home/dmitri/Code/test/video_capture-master/src/videocapture/CapabilityFinder.cpp.o
In file included from /usr/include/c++/4.8/algorithm:62:0,
                 from /home/dmitri/Code/test/video_capture-master/build/../include/videocapture/CapabilityFinder.h:44,
                 from /home/dmitri/Code/test/video_capture-master/src/videocapture/CapabilityFinder.cpp:1:
/usr/include/c++/4.8/bits/stl_algo.h: In instantiation of ‘_RandomAccessIterator std::__unguarded_partition(_RandomAccessIterator, _RandomAccessIterator, const _Tp&, _Compare) [with _RandomAccessIterator = __gnu_cxx::__normal_iterator<ca::Capability*, std::vector<ca::Capability> >; _Tp = ca::Capability; _Compare = bool (_)(ca::Capability&, ca::Capability&)]’:
/usr/include/c++/4.8/bits/stl_algo.h:2296:78:   required from ‘_RandomAccessIterator std::__unguarded_partition_pivot(_RandomAccessIterator, _RandomAccessIterator, _Compare) [with _RandomAccessIterator = __gnu_cxx::__normal_iterator<ca::Capability_, std::vectorca::Capability >; _Compare = bool (_)(ca::Capability&, ca::Capability&)]’
/usr/include/c++/4.8/bits/stl_algo.h:2337:62:   required from ‘void std::__introsort_loop(_RandomAccessIterator, _RandomAccessIterator, _Size, _Compare) [with _RandomAccessIterator = __gnu_cxx::__normal_iterator<ca::Capability_, std::vectorca::Capability >; _Size = long int; _Compare = bool (_)(ca::Capability&, ca::Capability&)]’
/usr/include/c++/4.8/bits/stl_algo.h:5490:44:   required from ‘void std::sort(_RAIter, _RAIter, _Compare) [with _RAIter = __gnu_cxx::__normal_iterator<ca::Capability_, std::vectorca::Capability >; _Compare = bool (_)(ca::Capability&, ca::Capability&)]’
/home/dmitri/Code/test/video_capture-master/src/videocapture/CapabilityFinder.cpp:140:72:   required from here
/usr/include/c++/4.8/bits/stl_algo.h:2263:35: error: invalid initialization of reference of type ‘ca::Capability&’ from expression of type ‘const ca::Capability’
    while (__comp(___first, __pivot))
                                   ^
/usr/include/c++/4.8/bits/stl_algo.h:2266:34: error: invalid initialization of reference of type ‘ca::Capability&’ from expression of type ‘const ca::Capability’
    while (__comp(__pivot, ___last))
                                  ^
make[2]: *_\* [CMakeFiles/videocapture.dir/home/dmitri/Code/test/video_capture-master/src/videocapture/CapabilityFinder.cpp.o] Error 1
make[1]: **\* [CMakeFiles/videocapture.dir/all] Error 2
make: **\* [all] Error 2
+ cd /home/dmitri/Code/test/video_capture-master/build/../install/linux-gcc-x86_64/bin
./release_x86.sh: 26: cd: can't cd to /home/dmitri/Code/test/video_capture-master/build/../install/linux-gcc-x86_64/bin
+ ./easy_opengl_example
./release_x86.sh: 33: ./release_x86.sh: ./easy_opengl_example: not found

**Comment by dignakov** [comment]
This is what I get on Arch:

---

---

---

[dmitri@CT-Arch build]$ ./release_x86.sh 
+ . ./set_variables.sh
++ d=/home/dmitri/Code/Test/video_capture/build
++ '[' '!' -d build.release ']'
+++ uname
++ '[' Linux = Darwin ']'
++++ uname -s
+++ expr substr Linux 1 5
++ '[' Linux = Linux ']'
++ is_linux=y
++ triplet=linux-gcc-x86_64
++ extern_path=/home/dmitri/Code/Test/video_capture/build/../extern/linux-gcc-x86_64
++ install_path=/home/dmitri/Code/Test/video_capture/build/../install/linux-gcc-x86_64
++ '[' y = y ']'
++ export LD_LIBRARY_PATH=:/home/dmitri/Code/Test/video_capture/build/../extern/linux-gcc-x86_64/lib/
++ LD_LIBRARY_PATH=:/home/dmitri/Code/Test/video_capture/build/../extern/linux-gcc-x86_64/lib/
++ '[' '!' -d /home/dmitri/Code/Test/video_capture/build/sources ']'
+ cd build.release
+ cmake -DCMAKE_BUILD_TYPE=Debug -DUSE_OPENGL=On -DUSE_GENERATE_X86=On -DUSE_GENERATE_IPHONE=Off -DUSE_GENERATE_IPHONE_SIMULATOR=Off -DUSE_GENERATE_RPI=Off -DUSE_DECKLINK=Off -DEXTERN_LIB_DIR=/home/dmitri/Code/Test/video_capture/build/../extern/linux-gcc-x86_64/lib -DEXTERN_INC_DIR=/home/dmitri/Code/Test/video_capture/build/../extern/linux-gcc-x86_64/include -DEXTERN_SRC_DIR=/home/dmitri/Code/Test/video_capture/build/../extern/linux-gcc-x86_64/src -DTINYLIB_DIR=/home/dmitri/Code/Test/video_capture/build/sources/tinylib/ -DCMAKE_INSTALL_PREFIX=/home/dmitri/Code/Test/video_capture/build/../install/linux-gcc-x86_64 ../
-- VideoCapture.USE_GENERATE_X86: On
-- VideoCapture.USE_GENERATE_IPHONE: Off
-- VideoCapture.USE_GENERATE_IPHONE_SIMULATOR: Off
-- VideoCapture.USE_GENERATE_RPI: Off
-- VideoCapture.USE_OPENGL: On
-- VideoCapture.USE_DECKLINK: Off
-- Configuring done
-- Generating done
-- Build files have been written to: /home/dmitri/Code/Test/video_capture/build/build.release
+ cmake --build . --target install --config Release
[ 61%] Built target videocapture
make[2]: **\* No rule to make target '../../extern/linux-gcc-x86_64/lib/libglfw3.a', needed by 'api_example'.  Stop.
CMakeFiles/Makefile2:60: recipe for target 'CMakeFiles/api_example.dir/all' failed
make[1]: **\* [CMakeFiles/api_example.dir/all] Error 2
Makefile:117: recipe for target 'all' failed
make: **\* [all] Error 2
+ cd /home/dmitri/Code/Test/video_capture/build/../install/linux-gcc-x86_64/bin
./release_x86.sh: line 26: cd: /home/dmitri/Code/Test/video_capture/build/../install/linux-gcc-x86_64/bin: No such file or directory
+ ./easy_opengl_example
./release_x86.sh: line 33: ./easy_opengl_example: No such file or directory

**Comment by roxlu** [comment]
I'm going to look into this in a couple of hours. Can you send me your email/skype?

**Comment by roxlu** [comment]
Hi dignakov after updating an old laptop which took about a day :) I fixed some issues on ubuntu. Could you give it a try? (Maybe do a clean clone).

**Comment by dignakov** [comment]
Hi,

Everything compiles and runs, tested Ubuntu (fresh image, and my normal system).

Thank you for looking into this, and please let me know if you'd like me to test anything in the future.
